baseURL = "https://www.kingesq.us/"
languageCode = "en-us"
title = "Jin-Ho King, Attorney at Law"
theme = "kingesq-theme"

[params]
    slogan = "Litigation with Impact"
    logo = "images/logo.png"
    favicon = "images/favicon.ico"
    author = "Jin-Ho King"
    address1 = "Jin-Ho King, Attorney at Law"
    address2 = "50 Congress St Ste 600 Boston MA 02109"
    address3 = "j@kingesq.us | +1 (617) 395-9571"
    disclaimer = "Prior results do not guarantee a similar outcome."
    description = "Jin-Ho King, Attorney at Law, focuses his practice on appeals and complex litigation matters."
    year = "2021"
    analytics = "UA-60108522-1"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "About"
        url = "/#about"
        weight = 2
    [[menu.main]]
        name = "Contact"
        url = "/#contact"
        weight = 3
    [[menu.main]]
        name = "Blog"
        url = "#"
        weight = 4